---
version: "2"

run:
  tests: true

linters:
  default: all
  disable:
    # restrictive
    - exhaustruct
    - varnamelen
    - nlreturn
    - funlen
    - nonamedreturns
    - gochecknoglobals
    - wsl
    - nakedret
    - err113
    # enable later
    - wrapcheck
    - revive
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
          allow:
            - $gostd
            - github.com/moderntv
            - github.com/cespare/xxhash
            - github.com/matryer/is

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  fix: true

output:
  formats:
    text:
      path: stdout
    tab:
      path: golangci-lint.out
      colors: false
    html:
      path: golangci-lint.out.html
