---
name: Basic checks

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Test
        run: make test TEST_VERBOSE=1

      - name: Lint
        run: make lint

      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          file: cp.out
