name: Basic checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: make test TEST_VERBOSE=1

      - name: Lint
        run: make lint

      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          file: coverage.txt
